# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 09:46
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import prueba.models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='direccion',
            field=models.TextField(default='direccion', verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='latitude',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='longitude',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casa',
            name='dueno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fotocasa',
            name='casa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='prueba.Casa'),
        ),
        migrations.AlterField(
            model_name='fotocasa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fotohabitacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fotoperfil',
            name='foto',
            field=models.FileField(upload_to=prueba.models.generar_ruta_image),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='casa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='prueba.Casa'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Número de teléfono inválido (debe tener de 9 a 15 dígitos)', regex='^\\+?1?\\d{9,15}$')], verbose_name='Numero de telefono'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=25, verbose_name='Etiqueta'),
        ),
    ]
