# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import prueba.models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_auto_20160317_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotoperfil',
            name='perfil',
        ),
        migrations.AddField(
            model_name='fotoperfil',
            name='casa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='prueba.Profile'),
        ),
        migrations.AlterField(
            model_name='fotoperfil',
            name='foto',
            field=models.FileField(upload_to=prueba.models.generar_ruta_image),
        ),
        migrations.AlterField(
            model_name='fotoperfil',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
