# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import prueba.models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_auto_20160317_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotoperfil',
            old_name='casa',
            new_name='perfil',
        ),
        migrations.AlterField(
            model_name='fotoperfil',
            name='foto',
            field=models.FileField(upload_to=prueba.models.generar_ruta_image),
        ),
    ]
