# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=200)),
                ('numHabitaciones', models.IntegerField()),
                ('numHabitacionesDisponibles', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('alquilerPorHabitaciones', models.BooleanField()),
                ('precioAlquiler', models.FloatField()),
                ('gastosComplementarios', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FotoCasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=200)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Casa')),
            ],
        ),
        migrations.CreateModel(
            name='FotoHabitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FotoPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Casa')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('evento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Conversacion')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNacimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('sexo', models.CharField(max_length=200)),
                ('trabajadorEstudiante', models.BooleanField()),
                ('campo', models.CharField(max_length=200)),
                ('fumador', models.BooleanField()),
                ('animalCompania', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('zonaBuscada', models.CharField(max_length=200)),
                ('inicioEstancia', models.DateTimeField(default=django.utils.timezone.now)),
                ('finEstancia', models.DateTimeField(default=django.utils.timezone.now)),
                ('instrumento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=200)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Perfil')),
                ('usuariosSimilares', models.ManyToManyField(to='web.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TagValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Perfil')),
                ('tagName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
                ('conversaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Conversacion')),
            ],
        ),
        migrations.AddField(
            model_name='mensaje',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Usuario'),
        ),
        migrations.AddField(
            model_name='fotoperfil',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Perfil'),
        ),
        migrations.AddField(
            model_name='fotohabitacion',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Habitacion'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Usuario'),
        ),
        migrations.AddField(
            model_name='casa',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Persona'),
        ),
    ]
