# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='titulo',
            field=models.CharField(default=datetime.datetime(2016, 3, 13, 18, 18, 7, 512349, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
