# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='alias',
            field=models.CharField(default='alias', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='password', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(default='a@a.a', max_length=200),
            preserve_default=False,
        ),
    ]
