# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='conversaciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Conversacion'),
        ),
    ]
