# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160204_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='verificado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
