# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 20:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_log_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ash', models.TextField(max_length=200)),
                ('creation_date', models.DateField(default=datetime.datetime(2016, 3, 14, 21, 16, 40, 597225))),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
