# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_usuario_verificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='perfil',
        ),
        migrations.AddField(
            model_name='perfil',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Persona'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fechaNacimiento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='finEstancia',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='inicioEstancia',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='usuariosSimilares',
            field=models.ManyToManyField(null=True, to='web.Persona'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
