# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20160204_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activation_key',
            field=models.CharField(default='key_de_prueba', max_length=40),
            preserve_default=False,
        ),
    ]
